<?php

namespace AppBundle\Repository;

/**
 * SiteObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
