<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Site;
use AppBundle\Entity\SiteObject;
use Doctrine\ORM\NoResultException;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retrieve site entity from token.
     * @param $token string
     * @return Site|null
     */
    public function retrieveSiteByToken($token){

        $qb = $this->createQueryBuilder("s");

        $qb->select("s");


        $qb->where( $qb->expr()->eq('s.token', '?1'));
        $qb->setParameter(1, $token);

        try {
            return $qb->getQuery()->getSingleResult();
        }catch (NoResultException $e){
            return null;
        }



    }





}
