<?php

namespace AppBundle\Repository;

/**
 * UserReactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReactionRepository extends \Doctrine\ORM\EntityRepository
{
}
