# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ["@doctrine"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }